apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  ports:
    - name: "8000"
      port: 8000            # The port the service listens on
      targetPort: 8000      # The port on the pod to which the traffic is forwarded
  selector:
    app: flask-app
  type: LoadBalancer
