apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
  ports:
    - name: "80"
      port: 80            # The port the service listens on
      targetPort: 80      # The port on the pod to which the traffic is forwarded
  selector:
    app: app
  type: LoadBalancer
