apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-username: bmV4dGNsb3Vk # this is taken by running echo -n nextcloud | base64
  postgres-password: bmV4dGNsb3Vk # this is taken by running echo -n nextcloud | base64
